# Disable new line at prompt start
add_newline = true

# Clean, minimal format
format = "$directory$git_branch$character"

# Prompt character
[character]
success_symbol = "[ ](bold blue)"
error_symbol = "[ ](bold red)"

# Git branch - compact
[git_branch]
format = "[ 󰘬 $branch](green)"
truncation_length = 4

# Directory - minimal
[directory]
format = "[$path](blue)"
truncation_length = 2
truncation_symbol = "./"

# Disable unused modules
[package]
disabled = true

[memory_usage]
disabled = true

[time]
disabled = true

[line_break]
disabled = true
